apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: elasticsearch
spec:
  templates:
    - name: elasticsearch
      metadata:
        labels:
          io.kompose.service: elasticsearch
      volumes:
        - name: config
          configMap:
            name: elasticsearch-hulk-config
            defaultMode: 077
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch-data
      container:
        name: elasticsearch
        command: ["/bin/bash"]
        args:
          [
            "-c",
            "chown -R elasticsearch /usr/local/hulk && su elasticsearch -c /usr/share/elasticsearch/bin/elasticsearch && tail -f /dev/null",
          ]
        ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
        securityContext:
          runAsUser: 0
        env:
          - name: discovery.type
            value: single-node
          - name: ES_JAVA_OPTS
            value: "-Dlog4j2.formatMsgNoLookups=true"
        volumeMounts:
          - name: data
            mountPath: /usr/local/hulk
          - name: config
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
        resources:
          limits:
            ephemeral-storage: "100Mi"
            memory: "7500Mi"
            cpu: "2000m"
          requests:
            ephemeral-storage: "100Mi"
            memory: "7500Mi"
            cpu: "2000m"
        startupProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - >-
                curl -XPUT 'localhost:9200/_settings' -H 'Content-Type: application/json' -d '{"settings": {"index.number_of_replicas": 0}}'
          initialDelaySeconds: 400
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 10
