apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose-copy.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  # TODO: Change this name to enterprise
  name: app
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
